### ISSUE TITLE
[Fabric 0.11.7 MC1.17.1 v: 1.3.1] Intense FPS lag when opening a cabinet

### ISSUE THREAD

**Issue by Vapaman** [AshIndigo/Filing_Cabinet#14]
FPS normally
![2021-09-28_23 25 48](https://user-images.githubusercontent.com/77460466/135161056-f90f4021-1c11-4aca-89df-047e0b19a15c.png)
FPS when viewing an cabinet inventory
![2021-09-28_23 26 06](https://user-images.githubusercontent.com/77460466/135160971-9e8437df-7cfa-44da-a10a-66e9845a7e18.png)
Bigger inventories mean much more lag
![2021-09-28_23 26 17](https://user-images.githubusercontent.com/77460466/135160975-65efc823-7a47-4969-80b3-c46195b0f2bf.png)

This is not a mod conflict issue as the lag is also present even when this is the only mod installed
![2021-09-28_23 38 49](https://user-images.githubusercontent.com/77460466/135162133-1f7661ff-e80b-4a8b-a7da-cf20ad6d1e7a.png)
I hope you can do something to this issue because it makes the mod borderline unusable for those with lower spec computers

**Comment by AshIndigo** [comment]
Thank you for the report! I'll see what I can do about this and get back to ya when I got something

**Comment by AshIndigo** [comment]
So good news, got an easy solution to this whole issue already sitting around. I was planning on releasing this version once 1.18 dropped. But might as well do it now if it fixes this performance issue.

If your willing to give it a quick test run, install [https://www.curseforge.com/minecraft/mc-mods/architectury-fabric](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric) and try using this build. Saves should be cross compatible between the current libgui based fabric version and this architectury version.

[1.17.1-StorageCabinet-1.4.0-fabric.zip (Make sure you extract the .jar)](https://github.com/AshIndigo/Storage_Cabinet/files/7252873/1.17.1-StorageCabinet-1.4.0-fabric.zip)

Still make a backup of your world though for good measure lest you risk item loss

**Comment by itsdinkd** [comment]
does this fix the performance issues with Indrev pipes (and using servo retriever) and Tom's Storage pipes?

**Comment by AshIndigo** [comment]
Yeah this build also includes the performance fix for cabinets that made their "is item valid" check faster. So it'll probably help with that as well

**Comment by itsdinkd** [comment]
Awesome, thank you!

**Comment by Kronon-Conspirator** [comment]
tested the 1.4.0 fix, good thing it fix the individual cabinets interaction. bad thing is the cabinet manager still lags intensely. just for ref on how many the cabinet is connected
![image](https://user-images.githubusercontent.com/72506952/135729229-df1ea173-9639-4ae4-8002-46c04995d62c.png)

**Comment by AshIndigo** [comment]
@Vapaman Any issues on your end with the build I uploaded?

Kronon for you though, I don't seem to notice any FPS drops in my dev environment when using the manager. If you want, I can try running your world/pack on my end to see if I can see it then. Is your pack available on CF by any chance?

**Comment by Kronon-Conspirator** [comment]
@AshIndigo sadly no as it has mods from multiple sources and even libraries for some reason CF doesn't want to approve of it (its the FTLib btw :D ). i do have a [discord server](https://discord.gg/YXm7vSBjdW) where i catalogue my pack if your still interested in looking into it.

**Comment by Vapaman** [comment]
Sorry for a late reply. Tested the build you linked (1.4.0) and the performance has greatly increased. The fps lag that I get is comparable to lag that vanilla chests cause when opened (a drop of 10 fps with no performance mods).

Edit: In this build the cabinets don't work properly since you can only put only one stack of items in it. The rest of the slots don't accept items, but I expect this will be fixed in a proper release.

**Comment by AshIndigo** [comment]
[1.17.1-StorageCabinet-1.4.1-fabric.zip](https://github.com/AshIndigo/Storage_Cabinet/files/7274720/1.17.1-StorageCabinet-1.4.1-fabric.zip)

@Vapaman Here, this new build should fix the cabinet related issues and maybe an extra performance boost. 

@Kronon-Conspirator If you want to try this as well, would be much appreciated

As always, keep a backup of your world and all that jazz before using this since it's a beta version

**Comment by Kronon-Conspirator** [comment]
![image](https://user-images.githubusercontent.com/72506952/135787393-3816c028-aadb-417e-a7b0-1cc3421dc7d2.png)
result from 1.4.1, like before individual interactions are improved drastically tho the yellow fps spikes seen in the pic is cause from opening the cabinets. unsure this is normal behavior.
and like before as well the cabinet manager spike still present

**Comment by AshIndigo** [comment]
Ok, spun up the pack myself and figured out how to work a profiler so I could do some better testing.

Looks like either my code or the mod Smooth Scrolling really doesn't like my GUI's. Would personally recommend disabling it until a fix is found.

REI doesn't seem to be happy as well, which I will have to look into. Turning it off via the keybind fixes the FPS issues from that as well. 

I'll post again later when I have a fix for this issues. Thank you all for reporting these issues

**Comment by Vapaman** [comment]
Nice, version 1.4.1 works and runs like a charm. Also seems like REIs performance is less than ideal to say it nicely.
